#!/bin/bash
#
# mkrelease 
#

# Preprocessing release version

VERSION=1.1b

if [ $# -eq 1 ] 
  then
  VERSION=$1
fi 

# Make distribution package
echo "---------------------------------------------------"
echo "Making distribution package - midapack release $VERSION"
echo "---------------------------------------------------"


#create library directories 
rm -rf midapack-$VERSION/

mkdir midapack-$VERSION/
mkdir midapack-$VERSION/src/
mkdir midapack-$VERSION/test/
mkdir midapack-$VERSION/doc/
mkdir midapack-$VERSION/include/
mkdir midapack-$VERSION/lib/
#
mkdir midapack-$VERSION/src/toeplitz/
mkdir midapack-$VERSION/src/mapmat/
mkdir midapack-$VERSION/test/toeplitz/
mkdir midapack-$VERSION/test/mapmat/
mkdir midapack-$VERSION/doc/fig/

#copies
# ./
cp README midapack-$VERSION/
cp LICENSE.LGPL3 midapack-$VERSION/
#cp Makefile midapack-$VERSION/
cp Makefile.in midapack-$VERSION/
cp configure midapack-$VERSION/

# include/
cp include/*.h midapack-$VERSION/include/
# doc/
cp doc/mkdoc.dox midapack-$VERSION/doc/
cp doc/README midapack-$VERSION/doc/
cp doc/fig/*.jpg midapack-$VERSION/doc/fig/
cp doc/fig/*.png midapack-$VERSION/doc/fig/
#cp doc/fig/*.gif midapack-$VERSION/doc/fig/
# src/
cp src/midapack.dox midapack-$VERSION/src/
# src/toeplitz/
cp src/toeplitz/toeplitz.c midapack-$VERSION/src/toeplitz/
cp src/toeplitz/toeplitz.h midapack-$VERSION/src/toeplitz/
cp src/toeplitz/toeplitz_block.c midapack-$VERSION/src/toeplitz/
cp src/toeplitz/toeplitz_gappy.c midapack-$VERSION/src/toeplitz/
cp src/toeplitz/toeplitz_rshp.c midapack-$VERSION/src/toeplitz/
cp src/toeplitz/toeplitz_nofft.c midapack-$VERSION/src/toeplitz/
cp src/toeplitz/toeplitz_seq.c midapack-$VERSION/src/toeplitz/
#cp src/toeplitz/toeplitz_seq.h midapack-$VERSION/src/toeplitz/
cp src/toeplitz/toeplitz_params.c midapack-$VERSION/src/toeplitz/
cp src/toeplitz/toeplitz.dox midapack-$VERSION/src/toeplitz/
#cp src/toeplitz/wscript midapack-$VERSION/src/toeplitz/
cp src/toeplitz/Makefile.in midapack-$VERSION/src/toeplitz/
# test/toeplitz/
DIR_TEST_TOEP=test/toeplitz/
cp $DIR_TEST_TOEP/testexple_mpi_stmm.c midapack-$VERSION/test/toeplitz/
cp $DIR_TEST_TOEP/testexple_mpi_stbmm.c midapack-$VERSION/test/toeplitz/
cp $DIR_TEST_TOEP/testexple_mpi_gstbmm.c midapack-$VERSION/test/toeplitz/
cp $DIR_TEST_TOEP/Makefile.in midapack-$VERSION/test/toeplitz/
# src/mapmat/
cp src/mapmat/*.c  midapack-$VERSION/src/mapmat/
cp src/mapmat/*.h  midapack-$VERSION/src/mapmat/
cp src/mapmat/*.dox  midapack-$VERSION/src/mapmat/
cp src/mapmat/Makefile.in midapack-$VERSION/src/mapmat/
# test/mapmat/
cp test/mapmat/*.c  midapack-$VERSION/test/mapmat/
cp test/mapmat/*.h  midapack-$VERSION/test/mapmat/
cp test/mapmat/*.f90  midapack-$VERSION/test/mapmat/
cp test/mapmat/*.mod midapack-$VERSION/test/mapmat/
cp test/mapmat/Makefile.in  midapack-$VERSION/test/mapmat/

#cp test/mapmat/test_pcg_mapmat.c  midapack-$VERSION/test/mapmat/
#cp test/mapmat/algo.c  midapack-$VERSION/test/mapmat/



#tar
rm -f midapack-$VERSION.tar.gz

tar -cvf midapack-$VERSION.tar midapack-$VERSION
gzip -9 midapack-$VERSION.tar


#cleaning
#rm -rf midapack-$VERSION/


