Import('mapmat_env')

files = [
    'alm.c',
    'als.c',
    'bitop.c',
    'butterfly.c',
    'cindex.c',
    'csort.c',
    'mapmat.c',
    'mapmatc.c',
    'ring.c',
]

obj = mapmat_env.SharedObject(source=files)

Return('obj')
